import type { Route } from './types'

export const ROUTES: Route[] = [
  {
    id: 'marathon',
    name: 'City Marathon', nameZh: '城市马拉松',
    totalMeters: 42195,
    color: '#6366f1',
    emoji: '🏃',
    description: 'The classic 42.195 km race',
    descriptionZh: '经典42.195公里马拉松全程',
    milestones: [
      { id: 'm1', name: 'Start Line', nameZh: '起跑线', meters: 0, description: "Race begins!", descriptionZh: '比赛开始！', emoji: '🚦' },
      { id: 'm2', name: '5 km', nameZh: '5公里', meters: 5000, description: 'Warmed up, finding rhythm', descriptionZh: '热身完毕，进入节奏', emoji: '💪' },
      { id: 'm3', name: 'Half', nameZh: '半程', meters: 21097, description: 'Halfway there!', descriptionZh: '已跑半程，继续加油！', emoji: '🌟' },
      { id: 'm4', name: 'The Wall', nameZh: '30公里墙', meters: 30000, description: 'The notorious wall — keep going!', descriptionZh: '"撞墙点"，坚持！', emoji: '🧱' },
      { id: 'm5', name: 'Finish!', nameZh: '终点线', meters: 42195, description: 'Marathon complete!', descriptionZh: '完成马拉松！', emoji: '🏅' },
    ],
    svgPath: 'M10,80 C20,20 40,60 60,40 C80,20 90,70 120,50 C140,35 150,75 170,60',
  },
  {
    id: 'great_wall',
    name: 'Great Wall Trek', nameZh: '长城徒步',
    totalMeters: 21196000,
    color: '#a16207',
    emoji: '🏯',
    description: 'Walk the entire length of the Great Wall',
    descriptionZh: '沿着长城走完全程',
    milestones: [
      { id: 'gw1', name: 'Shanhaiguan', nameZh: '山海关', meters: 0, description: 'Eastern terminus', descriptionZh: '长城东端起点', emoji: '🌅' },
      { id: 'gw2', name: 'Badaling', nameZh: '八达岭', meters: 600000, description: 'The most visited section', descriptionZh: '游客最多的段落', emoji: '🏔️' },
      { id: 'gw3', name: 'Midpoint', nameZh: '中段', meters: 10000000, description: 'Crossing the Loess Plateau', descriptionZh: '穿越黄土高原', emoji: '🌾' },
      { id: 'gw4', name: 'Jiayuguan', nameZh: '嘉峪关', meters: 21196000, description: 'Western terminus', descriptionZh: '长城西端终点', emoji: '🌄' },
    ],
    svgPath: 'M5,70 L25,50 L45,60 L65,30 L85,45 L105,25 L125,40 L145,20 L165,35 L175,25',
  },
  {
    id: 'tokyo_walk',
    name: 'Tokyo City Walk', nameZh: '东京城市漫步',
    totalMeters: 15000,
    color: '#db2777',
    emoji: '🗼',
    description: 'Asakusa to Shibuya through central Tokyo',
    descriptionZh: '从浅草到涩谷的都市散步',
    milestones: [
      { id: 't1', name: 'Senso-ji', nameZh: '浅草寺', meters: 0, description: 'Start at the historic temple', descriptionZh: '旅程从历史古刹出发', emoji: '⛩️' },
      { id: 't2', name: 'Ueno Park', nameZh: '上野公园', meters: 3000, description: 'Cherry blossoms in bloom', descriptionZh: '樱花盛开的公园', emoji: '🌸' },
      { id: 't3', name: 'Akihabara', nameZh: '秋叶原', meters: 6000, description: "Electronics paradise", descriptionZh: '电子科技的圣地', emoji: '🎮' },
      { id: 't4', name: 'Ginza', nameZh: '银座', meters: 10000, description: 'Luxury shopping district', descriptionZh: '奢华购物街区', emoji: '🛍️' },
      { id: 't5', name: 'Shibuya', nameZh: '涩谷', meters: 15000, description: "World's busiest crossing", descriptionZh: '世界最繁忙的十字路口', emoji: '🚶' },
    ],
    svgPath: 'M10,30 C30,60 50,20 70,50 C90,80 110,30 130,60 C150,90 160,40 175,50',
  },
  {
    id: 'paris_promenade',
    name: 'Paris Promenade', nameZh: '巴黎漫步',
    totalMeters: 12000,
    color: '#7c3aed',
    emoji: '🗼',
    description: 'Eiffel Tower to the Louvre',
    descriptionZh: '从埃菲尔铁塔到卢浮宫',
    milestones: [
      { id: 'p1', name: 'Eiffel Tower', nameZh: '埃菲尔铁塔', meters: 0, description: 'Under the iron lady', descriptionZh: '铁塔脚下出发', emoji: '🗼' },
      { id: 'p2', name: 'Champ de Mars', nameZh: '战神广场', meters: 1500, description: "Paris's green lung", descriptionZh: '巴黎绿肺', emoji: '🌿' },
      { id: 'p3', name: 'Seine River', nameZh: '塞纳河畔', meters: 5000, description: 'Strolling along the Seine', descriptionZh: '浪漫河边漫步', emoji: '🌊' },
      { id: 'p4', name: 'Notre-Dame', nameZh: '巴黎圣母院', meters: 8000, description: 'Gothic masterpiece', descriptionZh: '哥特式建筑瑰宝', emoji: '⛪' },
      { id: 'p5', name: 'The Louvre', nameZh: '卢浮宫', meters: 12000, description: "World's largest museum", descriptionZh: '世界最大博物馆', emoji: '🏛️' },
    ],
    svgPath: 'M10,70 C30,40 50,80 80,50 L100,60 C120,30 140,70 165,45 L175,50',
  },
  {
    id: 'silk_road',
    name: 'Silk Road', nameZh: '丝绸之路',
    totalMeters: 7000000,
    color: '#b45309',
    emoji: '🐪',
    description: "Xi'an to Rome along the ancient trade route",
    descriptionZh: '古代贸易路线，西安到罗马',
    milestones: [
      { id: 's1', name: "Xi'an", nameZh: '西安', meters: 0, description: 'Ancient capital, camel bells ring', descriptionZh: '古都出发，驼铃声声', emoji: '🏰' },
      { id: 's2', name: 'Dunhuang', nameZh: '敦煌', meters: 1800000, description: 'Mogao Caves, desert oasis', descriptionZh: '莫高窟，沙漠绿洲', emoji: '🕌' },
      { id: 's3', name: 'Samarkand', nameZh: '撒马尔罕', meters: 3500000, description: 'Central Asian gem', descriptionZh: '中亚古城', emoji: '🌙' },
      { id: 's4', name: 'Constantinople', nameZh: '君士坦丁堡', meters: 6000000, description: 'Where East meets West', descriptionZh: '东西方交汇', emoji: '🌉' },
      { id: 's5', name: 'Rome', nameZh: '罗马', meters: 7000000, description: 'The Eternal City', descriptionZh: '永恒之城', emoji: '🏛️' },
    ],
    svgPath: 'M5,50 L30,45 L55,60 L80,35 L105,55 L130,40 L155,65 L175,50',
  },
  {
    id: 'taiwan_circle',
    name: 'Taiwan Circle', nameZh: '台湾环岛',
    totalMeters: 900000,
    color: '#0891b2',
    emoji: '🏝️',
    description: 'Cycling around the island of Taiwan',
    descriptionZh: '骑行环绕台湾一圈',
    milestones: [
      { id: 'tw1', name: 'Taipei', nameZh: '台北出发', meters: 0, description: 'Heading south from Taipei', descriptionZh: '从台北出发向南', emoji: '🌆' },
      { id: 'tw2', name: 'Hualien', nameZh: '花莲', meters: 250000, description: 'Taroko Gorge', descriptionZh: '太鲁阁峡谷', emoji: '🏞️' },
      { id: 'tw3', name: 'Kenting', nameZh: '垦丁', meters: 500000, description: "Taiwan's southern tip", descriptionZh: '台湾最南端', emoji: '🌊' },
      { id: 'tw4', name: 'Tainan', nameZh: '台南', meters: 700000, description: 'Ancient capital, great food', descriptionZh: '古都美食之旅', emoji: '🍜' },
      { id: 'tw5', name: 'Back to Taipei', nameZh: '回到台北', meters: 900000, description: 'Circle complete!', descriptionZh: '完成环岛！', emoji: '🎉' },
    ],
    svgPath: 'M90,10 C140,10 170,50 160,90 C150,130 110,150 90,150 C70,150 30,130 20,90 C10,50 40,10 90,10',
  },
  {
    id: 'camino',
    name: 'Camino de Santiago', nameZh: '圣地亚哥之路',
    totalMeters: 800000,
    color: '#d97706',
    emoji: '🚶',
    description: 'The classic Spanish pilgrimage route',
    descriptionZh: '西班牙朝圣之路',
    milestones: [
      { id: 'c1', name: 'Saint-Jean', nameZh: '圣让小镇', meters: 0, description: 'French Pyrenees village', descriptionZh: '法国小镇出发', emoji: '⛰️' },
      { id: 'c2', name: 'Pamplona', nameZh: '潘普洛纳', meters: 75000, description: 'Running of the Bulls', descriptionZh: '奔牛节故乡', emoji: '🐂' },
      { id: 'c3', name: 'Burgos', nameZh: '布尔戈斯', meters: 280000, description: 'Gothic cathedral', descriptionZh: '哥特大教堂', emoji: '⛪' },
      { id: 'c4', name: 'León', nameZh: '莱昂', meters: 500000, description: 'Rest and resupply', descriptionZh: '中途休整', emoji: '🦁' },
      { id: 'c5', name: 'Santiago!', nameZh: '圣地亚哥', meters: 800000, description: 'Buen Camino!', descriptionZh: '朝圣终点！', emoji: '✝️' },
    ],
    svgPath: 'M10,50 C30,30 50,60 70,40 C90,20 110,55 130,35 C150,15 165,50 175,45',
  },
  {
    id: 'appalachian',
    name: 'Appalachian Trail', nameZh: '阿巴拉契亚山径',
    totalMeters: 3500000,
    color: '#16a34a',
    emoji: '🌲',
    description: "USA's longest footpath",
    descriptionZh: '美国东海岸最长徒步路线',
    milestones: [
      { id: 'a1', name: 'Springer Mtn', nameZh: '斯普林格山', meters: 0, description: 'Georgia start', descriptionZh: '佐治亚州起点', emoji: '🏔️' },
      { id: 'a2', name: 'Blue Ridge', nameZh: '蓝岭山脉', meters: 700000, description: 'Misty ridgelines', descriptionZh: '云雾缭绕的山脊', emoji: '☁️' },
      { id: 'a3', name: 'Shenandoah', nameZh: '谢南多厄', meters: 1500000, description: 'National park highlights', descriptionZh: '国家公园精华段', emoji: '🦌' },
      { id: 'a4', name: 'White Mountains', nameZh: '白山', meters: 2800000, description: 'Most challenging stretch', descriptionZh: '恶劣天气的挑战', emoji: '❄️' },
      { id: 'a5', name: 'Mt. Katahdin', nameZh: '卡塔丁山', meters: 3500000, description: 'Maine finale!', descriptionZh: '缅因州终点！', emoji: '🏁' },
    ],
    svgPath: 'M10,90 C20,70 30,85 40,60 C50,35 60,65 70,45 C80,25 90,55 100,30 C110,5 120,40 130,20 C140,5 155,35 165,15 L175,10',
  },
  {
    id: 'sahara',
    name: 'Sahara Crossing', nameZh: '撒哈拉穿越',
    totalMeters: 500000,
    color: '#92400e',
    emoji: '🏜️',
    description: "Cross the world's largest desert",
    descriptionZh: '穿越世界最大沙漠',
    milestones: [
      { id: 'sh1', name: 'Base Camp', nameZh: '起点营地', meters: 0, description: 'Departing at dawn', descriptionZh: '黎明前出发', emoji: '⛺' },
      { id: 'sh2', name: 'First Oasis', nameZh: '第一绿洲', meters: 100000, description: 'Water and rest', descriptionZh: '补充淡水，休整', emoji: '🌴' },
      { id: 'sh3', name: 'Erg Sea', nameZh: '沙丘海', meters: 250000, description: 'Endless dunes', descriptionZh: '无边无际的沙海', emoji: '🌊' },
      { id: 'sh4', name: 'Rock Art', nameZh: '岩画遗址', meters: 380000, description: 'Ancient civilization', descriptionZh: '古代文明的痕迹', emoji: '🗿' },
      { id: 'sh5', name: 'Finish Town', nameZh: '终点镇', meters: 500000, description: 'Crossing complete!', descriptionZh: '穿越完成！', emoji: '🎊' },
    ],
    svgPath: 'M10,50 L35,55 C50,60 55,40 75,45 C95,50 100,35 120,40 L145,50 C155,55 165,45 175,50',
  },
  {
    id: 'beijing_hutong',
    name: 'Beijing Hutong Walk', nameZh: '北京胡同漫游',
    totalMeters: 8000,
    color: '#dc2626',
    emoji: '🏮',
    description: 'Through the historic alleys of old Beijing',
    descriptionZh: '穿越北京老城的历史足迹',
    milestones: [
      { id: 'fc1', name: 'Drum Tower', nameZh: '鼓楼', meters: 0, description: 'Start at the ancient tower', descriptionZh: '从古楼出发', emoji: '🥁' },
      { id: 'fc2', name: 'Nanluoguxiang', nameZh: '南锣鼓巷', meters: 1500, description: 'Artsy hutong lane', descriptionZh: '文艺胡同', emoji: '🎨' },
      { id: 'fc3', name: 'Jingshan Park', nameZh: '景山公园', meters: 3500, description: 'Overlooking the Forbidden City', descriptionZh: '俯瞰故宫全景', emoji: '👁️' },
      { id: 'fc4', name: 'Forbidden City', nameZh: '故宫', meters: 5500, description: 'Imperial palace complex', descriptionZh: '紫禁城，皇家宫殿', emoji: '🏯' },
      { id: 'fc5', name: "Tian'anmen", nameZh: '天安门广场', meters: 8000, description: "Center of China's history", descriptionZh: '历史的中心', emoji: '🌟' },
    ],
    svgPath: 'M20,30 C35,50 50,25 65,45 C80,65 95,35 110,55 L125,60 C140,65 155,45 170,50 L175,52',
  },
]

export function getRoute(id: string): Route {
  return ROUTES.find(r => r.id === id) ?? ROUTES[0]
}
